network:
  ethernets:
    ens33:
      addresses:
        - 192.168.102.129/24
      routes:
        - to: 0.0.0.0/0
          via: 192.168.102.128
      nameservers:
        addresses:
          - 8.8.8.8
  version: 2
